"""Which TTF supplies Cyrillic for each TMP font asset of the game.

value: (ttf path relative to the repository root, wght for variable fonts or None, substitute)
substitute=True  -> another family; glyphs are scaled to the original 'H' height.
substitute=False -> same family (game's own TTF or a newer release with Cyrillic); rendered at PointSize.
"""
U = "fonts/"  # Ubuntu TTFs, identical to the Font assets inside the game
G = "fonts/google/"

FONT_MAP = {
    # game UI (Ubuntu, TTFs extracted from the game itself)
    "Ubuntu-Regular SDF": (U + "Ubuntu-Regular.ttf", None, False),
    "Ubuntu-Bold SDF": (U + "Ubuntu-Bold.ttf", None, False),
    "Ubuntu-Light SDF": (U + "Ubuntu-Light.ttf", None, False),
    "Ubuntu-Medium SDF": (U + "Ubuntu-Medium.ttf", None, False),
    "Ubuntu-Bold SDF SOFT MASKED": (U + "Ubuntu-Bold.ttf", None, False),
    "Ubuntu-BoldItalic SDF": (U + "Ubuntu-BoldItalic.ttf", None, False),
    "Ubuntu-Italic SDF": (U + "Ubuntu-Italic.ttf", None, False),
    "Ubuntu-Light SDF SOFT MASKED": (U + "Ubuntu-Light.ttf", None, False),
    "Ubuntu-Light more descender SDF": (U + "Ubuntu-Light.ttf", None, False),
    "Ubuntu-MediumItalic SDF": (U + "Ubuntu-MediumItalic.ttf", None, False),
    "LiberationSans SDF": ("fonts/LiberationSans-Regular.ttf", None, False),

    # in-game websites: same family, newer release has Cyrillic
    "SourceSansPro-Light SDF": (G + "sourcesans3/SourceSans3[wght].ttf", 300, False),
    "SourceSansPro-Regular SDF": (G + "sourcesans3/SourceSans3[wght].ttf", 400, False),
    "SourceSansPro-Semibold SDF": (G + "sourcesans3/SourceSans3[wght].ttf", 600, False),
    "SourceSansPro-Bold SDF": (G + "sourcesans3/SourceSans3[wght].ttf", 700, False),
    "Raleway-Regular SDF": (G + "raleway/Raleway[wght].ttf", 400, False),
    "Raleway-SemiBold SDF": (G + "raleway/Raleway[wght].ttf", 600, False),
    "Raleway-Bold SDF": (G + "raleway/Raleway[wght].ttf", 700, False),
    "Lato-Light SDF": (G + "lato/Lato-Light.ttf", None, False),
    "Lato-Regular SDF": (G + "lato/Lato-Regular.ttf", None, False),
    "Lato-Italic SDF": (G + "lato/Lato-Italic.ttf", None, False),
    "Lato-Bold SDF": (G + "lato/Lato-Bold.ttf", None, False),
    "Lato-BoldItalic SDF": (G + "lato/Lato-BoldItalic.ttf", None, False),
    "Lato-Black SDF": (G + "lato/Lato-Black.ttf", None, False),
    "Lato-BlackItalic SDF": (G + "lato/Lato-BlackItalic.ttf", None, False),
    "YanoneKaffeesatz-ExtraLight SDF": (G + "yanonekaffeesatz/YanoneKaffeesatz[wght].ttf", 200, False),
    "YanoneKaffeesatz-Light SDF": (G + "yanonekaffeesatz/YanoneKaffeesatz[wght].ttf", 300, False),
    "YanoneKaffeesatz-Regular SDF": (G + "yanonekaffeesatz/YanoneKaffeesatz[wght].ttf", 400, False),
    "YanoneKaffeesatz-Bold SDF": (G + "yanonekaffeesatz/YanoneKaffeesatz[wght].ttf", 700, False),
    "NotoSans-Regular SDF": (G + "notosans/NotoSans[wdth,wght].ttf", 400, False),
    "NotoSans-Bold SDF": (G + "notosans/NotoSans[wdth,wght].ttf", 700, False),
    "NotoSans-BoldItalic SDF": (G + "notosans/NotoSans-Italic[wdth,wght].ttf", 700, False),
    "NotoSerif-Regular SDF": (G + "notoserif/NotoSerif[wdth,wght].ttf", 400, False),
    "NotoSerif-Bold SDF": (G + "notoserif/NotoSerif[wdth,wght].ttf", 700, False),
    "NotoSerif-BoldItalic SDF": (G + "notoserif/NotoSerif-Italic[wdth,wght].ttf", 700, False),
    "Montserrat-Regular SDF": (G + "montserrat/Montserrat[wght].ttf", 400, False),
    "Montserrat-SemiBold SDF": (G + "montserrat/Montserrat[wght].ttf", 600, False),
    "Montserrat-ExtraBold SDF": (G + "montserrat/Montserrat[wght].ttf", 800, False),
    "Merriweather-Regular SDF": (G + "merriweather/Merriweather[opsz,wdth,wght].ttf", 400, False),
    "Merriweather-Bold SDF": (G + "merriweather/Merriweather[opsz,wdth,wght].ttf", 700, False),
    "Vollkorn-Regular SDF": (G + "vollkorn/Vollkorn[wght].ttf", 400, False),
    "Vollkorn-Bold SDF": (G + "vollkorn/Vollkorn[wght].ttf", 700, False),
    "Vollkorn-Italic SDF": (G + "vollkorn/Vollkorn-Italic[wght].ttf", 400, False),
    "Vollkorn-BoldItalic SDF": (G + "vollkorn/Vollkorn-Italic[wght].ttf", 700, False),
    "Bitter-Regular SDF": (G + "bitter/Bitter[wght].ttf", 400, False),
    "Lora-Regular SDF": (G + "lora/Lora[wght].ttf", 400, False),
    "AnonymousPro-Regular SDF": (G + "anonymouspro/AnonymousPro-Regular.ttf", None, False),

    # no Cyrillic in the family at all -> closest-looking substitute
    "Cambay-Regular SDF": (G + "ptsans/PT_Sans-Web-Regular.ttf", None, True),
    "Cambay-Bold SDF": (G + "ptsans/PT_Sans-Web-Bold.ttf", None, True),
    "Arvo-Regular SDF": (G + "robotoslab/RobotoSlab[wght].ttf", 400, True),
    "Arvo-Bold SDF": (G + "robotoslab/RobotoSlab[wght].ttf", 700, True),
    "Arvo-Italic SDF": (G + "bitter/Bitter-Italic[wght].ttf", 600, True),
    "Arvo-BoldItalic SDF": (G + "bitter/Bitter-Italic[wght].ttf", 800, True),
    "Oxygen-Regular SDF": (G + "firasans/FiraSans-Regular.ttf", None, True),
    "Oxygen-Bold SDF": (G + "firasans/FiraSans-Bold.ttf", None, True),
    "Signika-Light SDF": (G + "firasans/FiraSans-Light.ttf", None, True),
    "Signika-Regular SDF": (G + "firasans/FiraSans-Regular.ttf", None, True),
    "Signika-Bold SDF": (G + "firasans/FiraSans-SemiBold.ttf", None, True),
    "Dosis-Regular SDF": (G + "firasanscondensed/FiraSansCondensed-Light.ttf", None, True),
    "Dosis-SemiBold SDF": (G + "firasanscondensed/FiraSansCondensed-Regular.ttf", None, True),
    "Dosis-Bold SDF": (G + "firasanscondensed/FiraSansCondensed-Medium.ttf", None, True),
    "Dosis-ExtraBold SDF": (G + "firasanscondensed/FiraSansCondensed-SemiBold.ttf", None, True),
    "Cairo-Regular SDF": (G + "exo2/Exo2[wght].ttf", 400, True),
    "Cairo-Bold SDF": (G + "exo2/Exo2[wght].ttf", 700, True),
    "Cairo-Black SDF": (G + "exo2/Exo2[wght].ttf", 900, True),
    "Karla-Regular SDF": (G + "rubik/Rubik[wght].ttf", 400, True),
    "Karla-Bold SDF": (G + "rubik/Rubik[wght].ttf", 700, True),
    "WorkSans-Regular SDF": (G + "rubik/Rubik[wght].ttf", 400, True),
    "WorkSans-ExtraBold SDF": (G + "rubik/Rubik[wght].ttf", 800, True),
    "SecularOne-Regular SDF": (G + "rubik/Rubik[wght].ttf", 700, True),
    "DroidSans-Regular SDF": (G + "notosans/NotoSans[wdth,wght].ttf", 400, True),
    "DroidSans-Bold SDF": (G + "notosans/NotoSans[wdth,wght].ttf", 700, True),
    "DroidSerif-Regular SDF": (G + "notoserif/NotoSerif[wdth,wght].ttf", 400, True),
    "DroidSerif-Bold SDF": (G + "notoserif/NotoSerif[wdth,wght].ttf", 700, True),
    "DroidSerif-Italic SDF": (G + "notoserif/NotoSerif-Italic[wdth,wght].ttf", 400, True),
    "CabinCondensed-Bold SDF": (G + "firasanscondensed/FiraSansCondensed-SemiBold.ttf", None, True),
    "Cinzel-Bold SDF": (G + "cormorantsc/CormorantSC-Bold.ttf", None, True),
    "LeckerliOne-Regular SDF": (G + "lobster/Lobster-Regular.ttf", None, True),
    "Shrikhand-Regular SDF": (G + "lobster/Lobster-Regular.ttf", None, True),
    "CoveredByYourGrace-Regular SDF": (G + "caveat/Caveat[wght].ttf", 400, True),
}
